/**
 * Canonical skill labels for auto-tagging and `projects.ai_stack` validation.
 */
export const SKILL_ONTOLOGY = [
  "LangChain",
  "LangGraph",
  "CrewAI",
  "OpenAI API",
  "Anthropic Claude",
  "RAG",
  "Vector DB",
  "Pinecone",
  "Weaviate",
  "ChromaDB",
  "pgvector",
  "Python",
  "FastAPI",
  "n8n",
  "Zapier",
  "Make",
  "Prompt Engineering",
  "Fine-tuning",
  "Embeddings",
  "Function Calling",
  "AI Agents",
  "Multi-modal AI",
  "Whisper",
  "ElevenLabs",
  "GPT-4o",
  "Gemini",
  "Llama",
  "Mistral",
  "Hugging Face",
  "LlamaIndex",
  "Chainlit",
  "Streamlit",
  "Gradio",
  "Supabase",
  "PostgreSQL",
  "Redis",
  "TypeScript",
  "Next.js",
  "Vercel AI SDK",
  "Replicate",
  "Stable Diffusion",
  "DALL-E",
  "Computer Vision",
  "OCR",
  "NLP",
  "Text-to-SQL",
  "AI Workflow Automation",
  "AutoGen",
  "Semantic Kernel",
  "DSPy",
  "Instructor",
] as const satisfies readonly string[];
